### ISSUE TITLE
Abilifier 1.1.5(.1) - Issue: StatisticEffectData Extension Tag Match Breaks with some types of statistic modification

### ISSUE THREAD

**Issue by korgano** [BattletechModders/Abilifier#15] opened 2023-01-14 16:13 UTC
I have a StatisticEffectData Extension that worked prior to Abilifier 1.1.5(.1), but no longer functions.

```
{
            "Description" : {
                "Id" : "StatusEffect-ExtremeRange",
                "Name" : "ARMOR BYPASS",
                "Details" : "Very long and extreme range weapons bypass armor and deal structure damage to the target."
            },
            "effectType" : "StatisticEffect",
            "nature" : "Buff",
            "durationData" : {
                "duration" : -1
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "effectTargetType" : "Creator",
                "showInTargetPreview" : false,
                "showInStatusPanel" : false,
                "hideApplicationFloatie" : false
            },
            "statisticData" : {
                "statName" : "StructureDamagePerShot",
                "operation" : "Float_Add",
                "modValue" : "5.0",
                "modType" : "System.Single",
                "targetCollection" : "Weapon"
            }
        },
```

As a control, I placed the statistic effect data for The Bounty Hunter's Perfect Aim skill (see below) in the ability, and it functioned:
```

{
            "Description" : {
                "Id" : "StatusEffect-BH-PerfectAimStructureDamage",
                "Name" : "ARMOR BYPASS",
                "Details" : "The Bounty Hunter's attacks bypass armor and deal structure damage to the target.",
                "Icon" : "UixSvgIcon_specialAbility_HiredGuns"
            },
            "effectType" : "StatisticEffect",
            "nature" : "Buff",
            "durationData" : {
                "duration" : -1
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "effectTargetType" : "Creator",
                "showInTargetPreview" : false,
                "showInStatusPanel" : false,
                "hideApplicationFloatie" : false
            },
            "statisticData" : {
                "statName" : "StructureDamagePerShot",
                "operation" : "Float_Add",
                "modValue" : "5.0",
                "modType" : "System.Single",
                "targetCollection" : "Weapon"
            }
        }
```

The StatisticEffectData Extension is as follows:
```
"StatusEffect-ExtremeRange": {
		"TargetCollectionForSearch": "Component",
		"TargetCollectionTagMatch": [
			"NotSet"
		],
		"TargetComponentTagMatch": [
			"range_extreme"
		]
	},
	"StatusEffect-CloseRange": {
		"TargetCollectionForSearch": "Component",
		"TargetCollectionTagMatch": [
			"NotSet"
		],
		"TargetComponentTagMatch": [
			"range_close"
		]
	},
	"StatusEffect-StandardRange": {
		"TargetCollectionForSearch": "Component",
		"TargetCollectionTagMatch": [
			"NotSet"
		],
		"TargetComponentTagMatch": [
			"range_standard"
		]
	},
	"StatusEffect-LongRange": {
		"TargetCollectionForSearch": "Component",
		"TargetCollectionTagMatch": [
			"NotSet"
		],
		"TargetComponentTagMatch": [
			"range_long"
		]
	},
	"StatusEffect-VeryLongRange": {
		"TargetCollectionForSearch": "Component",
		"TargetCollectionTagMatch": [
			"NotSet"
		],
		"TargetComponentTagMatch": [
			"range_very-long"
		]
	},
	"StatusEffect-LongestRanges": {
		"TargetCollectionForSearch": "Component",
		"TargetCollectionTagMatch": [
			"NotSet"
		],
		"TargetComponentTagMatch": [
			"range_very-long",
			"range_extreme"
		]
	},
```

Oddly, other range tag based StatisticEffectData Extensions work... **except** for "StatusEffect-LongestRanges", which also is supposed to match the "range_extreme" tag.

(Also, BTW, I'm not sure if "StatusEffect-LongestRanges" would only work if a weapon had both tags. Documentation is unclear on this point.)

The Abilifier log (attached) provides no information, and the ModTek logs do not show any information either, as far as I can see.

**Comment by ajkroeg** [comment] 2023-01-14 18:27
1) No logs are attached.

2) Nothing about statistic effect extensions has changed in nearly a year. If they don't work now, they didn't work before. Your extensions all have: `TargetCollectionForSearch": "Component",` and `"TargetCollectionTagMatch": ["NotSet"],` which means that if you want the effect to apply to a unit, it must have a component with a tag of `NotSet`. If the `NotSet` tag is found on _any_ component of, then it will proceed to look further for components with a tag from `TargetComponentTagMatch` to apply the effect to.

3) `TargetComponentTagMatch` looks for *any* matching tag; so in the case of your `"StatusEffect-LongestRanges`, weapons with "range_very-long" or "range_extreme affected". Both are not required.

I've added some clarification to the documentation, as I realize I didn't explain that you could use `NotSet` for `TargetCollectionForSearch`.

**Comment by korgano** [comment] 2023-01-15 15:53
So I've done some more testing, and I have discovered that tag matching is **not** broken, but for some reason, specific StatisticEffect changes break when tag matching is applied.

So, for example, a StatisticEffect that does a `DamagePerShot` modification will work, regardless of tag matching. But `StructureDamagePerShot` will **not** work with **any** type of tag matching. This is why the Perfect Aim effect data works when using its stock `"ID": "StatusEffect-` value, but not when using `"ID": "StatusEffect-ExtremeRange"`.

i have added a log file, but I don't think it's particularly useful, as there doesn't seem to be any logging at the actual code fault points:
[Abilifier.log](https://github.com/BattletechModders/Abilifier/files/10420546/Abilifier.log)

I did try to use DNSpy-EX to get more data, but it's started giving me Thread Handler Exception errors that disable all breakpoints in Abilifier, so I wasn't able to get any data that way. I am unsure if this means there's a problem with BattleTech, DNSpy-EX, or both, so I'm providing the ability code so that it can be tested on a known good system.

(I used `"StatusEffect-StandardRange"` as part of the testing process to see if it was just the ExtremeRange/VeryLongRange/LongestRanges tags that were the problem.)

```
{
	"Description" : {
		"Id" : "AbilityDef_TargetFiring",
		"Name" : "TARGETED AND FIRING",
		"Details" : "PASSIVE: Very long and extreme range weapons bypass armor and deal structure damage to the target.",
		"Icon" : "UixSvgIcon_specialAbility_HiredGuns"
	},
	"ShortDesc" : "Hits Bypass Armor",
    "DisplayParams" : "ShowInMWTRay",
    "ReqSkill" : "Gunnery",
	"ReqSkillLevel" : 8,
	"ActivationTime" : "Passive",
	"EffectData" :
	[
		{
            "Description" : {
                "Id" : "StatusEffect-VeryLongRange",
                "Name" : "ARMOR BYPASS",
                "Details" : "The Bounty Hunter's attacks bypass armor and deal structure damage to the target.",
                "Icon" : "UixSvgIcon_specialAbility_HiredGuns"
            },
            "effectType" : "StatisticEffect",
            "nature" : "Buff",
            "durationData" : {
                "duration" : -1,
                "stackLimit": 1
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "effectTargetType" : "Creator",
                "showInTargetPreview" : false,
                "showInStatusPanel" : false,
                "hideApplicationFloatie" : false
            },
            "statisticData" : {
                "statName" : "StructureDamagePerShot",
                "operation" : "Float_Add",
                "modValue" : "5.0",
                "modType": "System.Single",
                "additionalRules": "NotSet",
                "targetCollection": "Weapon",
                "targetWeaponCategory": "NotSet",
                "targetWeaponType": "NotSet",
                "targetAmmoCategory": "NotSet",
                "targetWeaponSubType": "NotSet"
            }
        },
        {
            "Description" : {
                "Id" : "StatusEffect-StandardRange",
                "Name" : "ARMOR BYPASS",
                "Details" : "The Bounty Hunter's attacks bypass armor and deal structure damage to the target.",
                "Icon" : "UixSvgIcon_specialAbility_HiredGuns"
            },
            "effectType" : "StatisticEffect",
            "nature" : "Buff",
            "durationData" : {
                "duration" : -1,
                "stackLimit": 1
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "effectTargetType" : "Creator",
                "showInTargetPreview" : false,
                "showInStatusPanel" : false,
                "hideApplicationFloatie" : false
            },
            "statisticData" : {
                "statName" : "StructureDamagePerShot",
                "operation" : "Float_Add",
                "modValue" : "5.0",
                "modType": "System.Single",
                "additionalRules": "NotSet",
                "targetCollection": "Weapon",
                "targetWeaponCategory": "NotSet",
                "targetWeaponType": "NotSet",
                "targetAmmoCategory": "NotSet",
                "targetWeaponSubType": "NotSet"
            }
        }
	],
    "IsPrimaryAbility": true
}
```

**Comment by ajkroeg** [comment] 2023-01-15 20:09
It works perfectly fine with StructureDamagePerShot. And yes, I checked. More than likely you have a stackLimit issue since all yours have `"stackLimit": 1`. Even if an effect is changing a completely different statistic, stackLimit still applies if the *effect ID in the description* is the same.

For example, in your above "test" example you've used`StatusEffect-StandardRange`... a quick check through your repo shows me that this ability: https://github.com/korgano/SkillTreeRebuild/blob/cb36e16bbc51ff5cc6cf46fb96dc6558f19d57ec/Abilities/AbilityDef_JackAll.json is already using "StatusEffect-StandardRange" at Gunnery 6. And in fact, I can guess that only the DamagePerShot effect from that is actually working, since the CriticalChanceMultiplier will *also* hit the same stackLimit.

**Comment by korgano** [comment] 2023-01-16 15:52
So I've changed the StackLimits to -1 and I still get the same behavior when I switch the status effect ID from a generic one to one in the StatisticEffectData Extension list.

Could this be a result of some conflict between Harmony patches or a lack of a dependency? I have experienced at least one possible example of such an issue in the past.

I am attaching the Harmony summary log in case that is a possibility:
[harmony_summary.txt](https://github.com/BattletechModders/Abilifier/files/10427383/harmony_summary.txt)

**Comment by ajkroeg** [comment] 2023-01-16 18:25
Nope, not a conflict or lack of dependency. The only external dependency Abilifier has is CAE, and only if you're using that release version. Do your basic troubleshooting. Start from a known config that works, and work from there. If you're adding tags to components on an assembled mech, the mech will likely need to be stored/re-readied to get the component tags to refresh. If you're changing ability names, you'll probably need to retrain the pilot. Is _anything_ from the ability you're trying to test working? Does the actual ability work if you don't try to run it through an EffectExtension? If not, there's your problem. If it does then you've either got a misconfigured EffectDataExtensions.json, or the component you're expecting the effect to apply to does not have the proper tags.

[test example.zip](https://github.com/BattletechModders/Abilifier/files/10428429/test.example.zip)

There's an example that works. Proper component tag on an mlas, Your structure damage effectData added to the Guts 5 Bulwark ability, and both reflected in `EffectDataExtensions.json`. Works fine.

Best practice for stackLimit is probably to keep it at 1 (so the effect doesn't stack with itself), and just ensure that the actual effect ID is unique.

`BATTLETECH/Mods/.modtek/battletech_log.txt` and/or `BATTLETECH/Mods/.modtek/battletech_log_cleaned.txt` will have lines like 

`19:37:31.7908640 CombatLog.AbilitiesAndEffects [LOG] Spider gains effect HeatSinkCapacity from self` which are useful to see if the effect is actually applying (it pulls from the `Description.Name` field of the effect).

**Comment by korgano** [comment] 2023-01-16 20:42
I am glad you provided a sample of useful log output, because it seems like there's a potentially related issue that is preventing logging from happening. It seems that the loggers might be affected by something, which could also be affecting the rest of Abilifier.

I did disable anti-virus for this quick test run to verify logger functionality, and as far as I can tell, the logger should be activating, but is not:
[ModTek-log.txt](https://github.com/BattletechModders/Abilifier/files/10429373/ModTek-log.txt)

**Comment by ajkroeg** [comment] 2023-01-16 21:49
if you're not getting _any_ logging then you've probably broken your DebugSettings file somehow. regardless that is not an Abilifier problem. once you do get the logs working, the useful information will be in `battletech_log_cleaned.txt`, not in the modtek log.

i do see two copies of this
```
00:00:16.7995396 ModTek [LOG] 	Add: AbilityDef_TargetFiring - Copy (AbilityDef): SkillTreeRebuild\Abilities\AbilityDef_TargetFiring - Copy.json
00:00:16.8000237 ModTek [LOG] 	Add: AbilityDef_TargetFiring (AbilityDef): SkillTreeRebuild\Abilities\AbilityDef_TargetFiring.json
```
 so make sure you're actually making changes to and checking the correct copy.

**Comment by korgano** [comment] 2023-01-25 22:20
Having updated to 1.1.6 and installed the latest ModTek v3.1.15+3, as well as sorted out the log settings, I have new data.

Example Statistic Effect:
```
{
            "durationData" : {
                "duration" : -1,
                "stackLimit" : -1
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "effectTargetType" : "Creator",
                "showInStatusPanel" : false
            },
            "effectType" : "StatisticEffect",
            "Description" : {
                "Id" : "StatusEffect-CloseRange-STB",
                "Name" : "SUPPORT WEAPON STAB DAMAGE INCREASE",
                "Details" : "Support weapon attacks deal 10% more damage.",
                "Icon" : "uixSvgIcon_ability_CIFS2"
            },
            "nature" : "Buff",
            "statisticData": {
				"modType": "System.Single",
				"modValue": "1",
				"operation": "Float_Add",
				"statName": "Instability",
				"targetAmmoCategory": "NotSet",
				"targetCollection": "Weapon",
				"targetWeaponCategory": "NotSet",
				"targetWeaponSubType": "NotSet",
				"targetWeaponType": "NotSet"
			}
        },
```

If EffectDataExtension is
```
	"StatusEffect-CloseRange-STB": {
		"TargetCollectionForSearch": "Component",
		"TargetCollectionTagMatch": [
			"NotSet"
		],
		"TargetComponentTagMatch": [
			"range_close"
		]
	},
```
**or**
```
	"StatusEffect-CloseRange-STB": {
		"TargetCollectionForSearch": "Component",
		"TargetComponentTagMatch": [
			"range_close"
		]
	},
```
the Statistic Effect will **not** be applied, and no log entry is made.

If EffectDataExtension is
```
"StatusEffect-CloseRange-STB": {
		"TargetComponentTagMatch": [
			"range_close"
		]
	},
```
the Statistic Effect **will** be applied, the statistic will be visibly modified in game, **and** a log entry made.

I have not yet tried to debug with DNSpy, but will update if I can get any results.

**Comment by ajkroeg** [comment] 2023-01-25 22:34
in the 1st example, its first checking that the unit has _any_ component with a tag called "NotSet" AND THEN checks to see if there are any components with tag "range_close" (which are the ones that actually get the effect applied to them)

2nd example is basically an invalid/incomplete configuration. It's effectively checking the unit for a component with no component tags at all, which is probably not a thing that exists.

3rd example is fine, as its just bypassing the initial check (because TargetCollectionForSearch is undefined/NotSet) and only applying the effect to components with the tag "range_close"

this is all working as intended.

**Closed as completed by ajkroeg** 2023-01-25 22:34 UTC
