### ISSUE TITLE
AbilityRealizer: Unable to read PilotTags from PilotDefs in .modtek cache?

### ISSUE THREAD

**Issue by korgano** [BattletechModders/Abilifier#21] opened 2023-04-26 21:29 UTC
Abilifier 4.0.0 w/ Ability Realizer integration

Expected behavior:

- ModTek executes Advanced JSON merge to replace PilotTag list in targeted PilotDef with new list including tag to be detected by Ability Realizer `IgnorePilotsWithTags` field (in this specific case)
- Game loads modified JSON
- Game generates OPFOR for mission based on contract JSON file
- Game selects modified PilotDef JSON as part of OPFOR
- Ability Realizer checks modified PilotDef tags, detects tag for `IgnorePilotsWithTags`
- Ability Realizer does not provide pilot with updated traits list from SimGameConstants skill tree 

Actual behavior:

- ModTek executes Advanced JSON merge to replace PilotTag list in targeted PilotDef with new list including tag to be detected by Ability Realizer `IgnorePilotsWithTags` field
- Game loads modified JSON
- Game generates OPFOR for mission based on contract JSON file
- Game selects modified PilotDef JSON as part of OPFOR
- Ability Realizer fails to check PilotDef tags/checks original PilotDef/cannot detect tags in modified PilotDef?
- Ability Realizer provides pilot with updated traits list from SimGameConstants skill tree 

I am unsure what is actually happening, as it seems to only affect PilotDefs* that have had JSON merge changes, despite the rest of Abilifier/Ability Realizer detecting and handling other merged JSONs without issues (see list of merged JSONs below):
[Merge-Dump.txt](https://github.com/BattletechModders/Abilifier/files/11337406/Merge-Dump.txt)

*I have not yet tested `ComponentTag` matching after a JSON merge replacing the tag list, nor `FactionAbility` or `PilotTag` detection.

**Comment by ajkroeg** [comment] 2023-04-27 21:16
Neither Abilifier nor AbilityRealizer have the ability to ignore parts of a PilotDef, or "only look at the original." There is only one PilotDef; the loaded one.

These look like merges on AI Pilots only, so unless you're seeing traits updated in the Abilifier or battletech_log (if so, where are those logs?), I'm not sure how you're able to determine it's giving them the traits from the updated tree. That log snippet only says "something merged" but doesn't show what the actual result of the merge is. Have you confirmed the PilotDefs in the cache actually have the modified tags? Lastly, changes to PilotDefs do not transfer to pilots you already have in your barracks; you have to retrain them.

If you are having trouble getting your Advanced JSON merges to work, its best to ask for assistance on one of the discord servers. If you think you've found a bug with JSON merges, that is best reported on the modtek repo.

**Closed as completed by ajkroeg** 2023-04-27 21:16 UTC

**Comment by korgano** [comment] 2023-04-27 21:33
> These look like merges on AI Pilots only, so unless you're seeing traits updated in the Abilifier or battletech_log (if so, where are those logs?), I'm not sure how you're able to determine it's giving them the traits from the updated tree. That log snippet only says "something merged" but doesn't show what the actual result of the merge is. Have you confirmed the PilotDefs in the cache actually have the modified tags?

I have:

- Confirmed the PilotDefs in the cache have the tags.
- Confirmed that AI pilots have the traits updated (see the attached file - the relevant units are Orion, Hatchetman, Assassin, and turrets, as well as Abilifier log)
- Abilifier log shows that dumping the settings from Ability Realizer does work, and that it is adding the abilities

Example merge code here:
```
{
    "TargetID": "pilot_d7_turret",
    "Instructions": [
        {
            "JSONPath": "PilotTags.items",
            "Action": "Replace",
            "Value": [
                "pilot_npc_gunner",
                "pilot_npc_dynamic",
                "pilot_turret_d7",
                "base_skills_only"
            ]
        }
    ]
}
```

The logs show Ability Realizer's failure to detect/respect the designated `"IgnorePilotsWithTags"`.

[Abilifier.log](https://github.com/BattletechModders/Abilifier/files/11348059/Abilifier.log)
[Ability-Dump.txt](https://github.com/BattletechModders/Abilifier/files/11348045/Ability-Dump.txt)

**Comment by ajkroeg** [comment] 2023-04-27 21:51
Thats Abilifier doing that, not AbilityRealizer. Abilifier always autofills Traits (not Abilities; distinguished by `IsPrimaryAbility` in the def) from the tree. been that way for at least a couple months now, since v1.1.something
